import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "./admin/dashboard/actors",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "./transactions",
    title: "Transactions",
    moduleName: "transactions",
    iconType: "feather",
    icon: "activity",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "./transactions/atms-transactions",
        title: "ATM Transactions",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./transactions/tellers-transactions",
        title: "Tellers Transactions",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./transactions/mpesa-transactions",
        title: "Mpesa Transactions",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./transactions/funds-transactions",
        title: "Funds Transfers",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./transactions/back-office-transactions",
        title: "Back- Office Transactions",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./transactions/end-of-day-transactions",
        title: "EOD Transactions",
        moduleName: "transactions",
        iconType: "feather",
        icon: "activity",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
    ],
  },
  
  {
    path: "./tellers",
    title: "Tellers",
    moduleName: "tellers",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },

  {
    path: "./reports",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "copy",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "reports/mpesa-reports",
        title: "M-pesa",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/funds-transfer-report",
        title: "Funds Transfer",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/international-money-transfer",
        title: "International Money Transfer",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/forex",
        title: "Forex",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
    ],
   
 
  },
  {
    path: "./back-office",
    title: "Back- Office",
    moduleName: "back-office",
    iconType: "feather",
    icon: "database",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "./back-office/referrals",
        title: "Referrals",
        moduleName: "back-office",
        iconType: "feather",
        icon: "database",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./back-office/modify-teller",
        title: "Modify Teller",
        moduleName: "back-office",
        iconType: "feather",
        icon: "database",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "./back-office/add-teller",
        title: "Add Teller",
        moduleName: "back-office",
        iconType: "feather",
        icon: "database",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
    ],
  },
  
]
 