import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "./admin/dashboard/actors",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "./reports",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "copy",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "reports/mpesa-reports",
        title: "M-pesa",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/funds-transfer-report",
        title: "Funds Transfer",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/international-money-transfer",
        title: "International Money Transfer",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "reports/forex",
        title: "Forex",
        moduleName: "reports",
        iconType: "feather",
        icon: "credit-card",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ADMIN"],
        submenu: [],
      },
    ],
   
 
  },
  {
    path: "./tellers",
    title: "Tellers",
    moduleName: "tellers",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  
  
]
